name: Code Quality Checks

on:
  push:

jobs:
  code-quality:
    name: Code Quality Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Load Environment
        run: |
          cat .env.example >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          poetry install

      - name: Format Code with Black
        run: |
          poetry run black --check --line-length 79 .

      - name: Sort Imports with isort
        run: |
          poetry run isort --check --profile black .

      - name: Lint Code with Flake8
        run: |
          poetry run flake8 .

      - name: Type Check with Pyre
        run: |
          sed -i 's|/root|/home/runner|g' .pyre_configuration && poetry run pyre check

      - name: Run Tests with Coverage
        run: |
          poetry run coverage run src/manage.py test
          poetry run coverage report
          poetry run coverage html
